name: Windows

on: [push, workflow_dispatch]

jobs:
  r20:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/loop.bat -OutFile loop.bat
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok.
      run: .\ngrok\ngrok.exe authtoken 2fs9Dhp3L54cogojUoiOZjFAuQ0_YKbZabjHKAFb7TfDG4ns
    - name: Enabling access to Windows OS.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Open Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region us-cal-1 3389"'
    - name: Сonnect to your Windows OS.
      run: cmd /c start.bat
    - name: Successfully made!You can close the tab now.
      run: cmd /c loop.bat

  r21:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/loop.bat -OutFile loop.bat
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok.
      run: .\ngrok\ngrok.exe authtoken 2g0STdUUKW9an0Nm3tkM1aHTvRl_6xBweJrrndrVSFFfj6ZRQ
    - name: Enabling access to Windows OS.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Open Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region us-cal-1 3389"'
    - name: Сonnect to your Windows OS.
      run: cmd /c start.bat
    - name: Successfully made!You can close the tab now.
      run: cmd /c loop.bat

  r22:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/loop.bat -OutFile loop.bat
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok.
      run: .\ngrok\ngrok.exe authtoken 2g0cdb2pgvwRZLodc7Ab3hMGEgl_6ySH3RmgMoE12mQNk3FD4
    - name: Enabling access to Windows OS.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Open Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region us-cal-1 3389"'
    - name: Сonnect to your Windows OS.
      run: cmd /c start.bat
    - name: Successfully made!You can close the tab now.
      run: cmd /c loop.bat

  r23:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/loop.bat -OutFile loop.bat
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok.
      run: .\ngrok\ngrok.exe authtoken 2g0oVlJcZRPSwmf3WP3ARkFGDBB_4TouLnxxys4EmEVG9VGd6
    - name: Enabling access to Windows OS.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Open Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region us-cal-1 3389"'
    - name: Сonnect to your Windows OS.
      run: cmd /c start.bat
    - name: Successfully made!You can close the tab now.
      run: cmd /c loop.bat

  r24:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/VMOSUI/Windows-OS/main/loop.bat -OutFile loop.bat
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok.
      run: .\ngrok\ngrok.exe authtoken 2g3NNu7D9KcyDccJgnaeS3lHpQe_6zu5HsUBDwZ8AsZDmv4Eo
    - name: Enabling access to Windows OS.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Open Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region us-cal-1 3389"'
    - name: Сonnect to your Windows OS.
      run: cmd /c start.bat
    - name: Successfully made!You can close the tab now.
      run: cmd /c loop.bat